<?php

use Illuminate\Database\Seeder;

class pel2TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
     public function run()
     {
     $records =
     [
       ['tel1Number' => '1000', 'pel2Number' => '1.01', 'pel2Title' => 'Annual Leave', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '1.02', 'pel2Title' => 'Personnal Business Leave', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '1.03', 'pel2Title' => 'Other Leave', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '1.04', 'pel2Title' => 'Medical Leave', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '1.05', 'pel2Title' => 'Bank Holiday', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '1.06', 'pel2Title' => 'Leave without Pay', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.01', 'pel2Title' => 'No Job', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.02', 'pel2Title' => 'Training-Training Code to be provided', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.03', 'pel2Title' => 'Internal Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.04', 'pel2Title' => 'Hours awaitng projects- Tender code to be provided', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.05', 'pel2Title' => 'Non-billable assignment', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.11', 'pel2Title' => 'Non-billable project step 1', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.12', 'pel2Title' => 'Non-billable project step 2', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.13', 'pel2Title' => 'Non-billable project step 3', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.21', 'pel2Title' => 'Procedure/calculation sheet step 1', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.22', 'pel2Title' => 'Procedure/calculation sheet step 2', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.31', 'pel2Title' => 'Personal goal step 1', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '2.32', 'pel2Title' => 'Personal goal step 2', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '3.01', 'pel2Title' => 'Bussiness Development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '3.02', 'pel2Title' => 'Tender-Tender Code to be provided', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '3.03', 'pel2Title' => 'Client-Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '3.04', 'pel2Title' => 'Tender Tracking', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '3.05', 'pel2Title' => 'Vendor registration - Vender name to be provided', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '3.06', 'pel2Title' => 'Prospect review and contact', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '4.01', 'pel2Title' => 'Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '5.01', 'pel2Title' => 'IT', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '6.01', 'pel2Title' => 'Office Administration', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '7.01', 'pel2Title' => 'HR', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '8.01', 'pel2Title' => 'Travel', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '9.01', 'pel2Title' => 'QA/QC-Procedure Development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '9.02', 'pel2Title' => 'QA/QC-KPI', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '9.03', 'pel2Title' => 'QA/QC-Non Conformance', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '9.04', 'pel2Title' => 'QA/QC-Others', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '9.05', 'pel2Title' => 'QA/QC-Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '10.01', 'pel2Title' => 'Other', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '11.01', 'pel2Title' => 'Safety', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '11.02', 'pel2Title' => 'Incident lost time incident', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1000', 'pel2Number' => '11.03', 'pel2Title' => 'Incident report and resolution', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1509', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1509', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1509', 'pel2Number' => '2.01', 'pel2Title' => 'Design Basis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1509', 'pel2Number' => '2.02', 'pel2Title' => 'Free Span Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1509', 'pel2Number' => '2.03', 'pel2Title' => 'Free Span Intervention Reccomendation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1509', 'pel2Number' => '2.04', 'pel2Title' => 'Free Span Intervention Specification', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1509', 'pel2Number' => '2.05', 'pel2Title' => 'Inspection Methodology Recommendation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1509', 'pel2Number' => '2.06', 'pel2Title' => 'Free Span Assessment Methodology', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1509', 'pel2Number' => '3.01', 'pel2Title' => 'Training', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1510', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1510', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1510', 'pel2Number' => '2.01', 'pel2Title' => 'Design Basis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1510', 'pel2Number' => '2.02', 'pel2Title' => 'Detail Engineering', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1510', 'pel2Number' => '2.03', 'pel2Title' => 'Detail Drafting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1510', 'pel2Number' => '3.01', 'pel2Title' => 'LARS Skid Detail Engineering', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1510', 'pel2Number' => '4.02', 'pel2Title' => 'LARS Accommodation Project Engineering', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '2.01', 'pel2Title' => 'Pipeline Routing Report', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '2.02', 'pel2Title' => 'Pipeline Soil Interaction Assessment Report', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '2.03', 'pel2Title' => 'Geohazard Study', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '2.04', 'pel2Title' => 'PLET Structural Anlaysis Report', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '2.05', 'pel2Title' => 'Document Review', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '2.06', 'pel2Title' => 'Geotechnical Design for Flowline - 12AG0104GT-FL', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '2.07', 'pel2Title' => 'Geotechnical Design for Structures - 12AG0104GT-ST', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '2.08', 'pel2Title' => 'Geotechnical Design for Structures - 12AG0104GT-ST (Manifold)', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '2.08a', 'pel2Title' => 'Geotechnical Design for Structures - 12AG0104GT-ST (Manifold) - Verification', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '3.01', 'pel2Title' => 'Coral South Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1512', 'pel2Number' => '4.01', 'pel2Title' => 'OCTP Support - Holdback Anchor', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1514', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1514', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1514', 'pel2Number' => '2.01', 'pel2Title' => 'Lateral Buckling Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1517', 'pel2Number' => '2.01', 'pel2Title' => 'Drafting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1519', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1519', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1519', 'pel2Number' => '2.01', 'pel2Title' => 'Bid Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1519', 'pel2Number' => '3.01', 'pel2Title' => 'PLET Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1519', 'pel2Number' => '4.01', 'pel2Title' => 'ILT Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1519', 'pel2Number' => '5.01', 'pel2Title' => 'Pigging Structure Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1519', 'pel2Number' => '6.01', 'pel2Title' => 'PLR Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1522', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1522', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1522', 'pel2Number' => '2.01', 'pel2Title' => 'Geotechnical Engineering Support 1', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1522', 'pel2Number' => '3.01', 'pel2Title' => 'Geotechnical Engineering Support 2', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1522', 'pel2Number' => '4.01', 'pel2Title' => 'Mooring Pile Dimension', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1530', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1530', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1530', 'pel2Number' => '2.01', 'pel2Title' => 'Structural Engineering Support - Thailand', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1530', 'pel2Number' => '2.02', 'pel2Title' => '3D Designer Support - Thailand', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1530', 'pel2Number' => '3.01', 'pel2Title' => 'Structural Engineering Support - Singapore', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1530', 'pel2Number' => '3.02', 'pel2Title' => '3D Designer Support - Singapore', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1530', 'pel2Number' => '4.01', 'pel2Title' => 'Structural Engineering Support - Malaysia', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1530', 'pel2Number' => '4.02', 'pel2Title' => '3D Designer Support - Malaysia', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1601', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1601', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1601', 'pel2Number' => '2.01', 'pel2Title' => 'Helideck Design Verification', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1602', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1602', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1602', 'pel2Number' => '2.01', 'pel2Title' => 'Design Basis Development and Survey Data Review', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1602', 'pel2Number' => '2.02', 'pel2Title' => 'Level 2 Free Span Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1602', 'pel2Number' => '2.03', 'pel2Title' => 'Level 3 Free Span Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1602', 'pel2Number' => '2.04', 'pel2Title' => 'Free Span Intervention and Rectification Recommendation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1602', 'pel2Number' => '9.01', 'pel2Title' => 'Free Mitigation Technical Note', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1604', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1604', 'pel2Number' => '2.01', 'pel2Title' => 'Developing Model', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1604', 'pel2Number' => '2.02', 'pel2Title' => 'Verify integrity, Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1604', 'pel2Number' => '2.03', 'pel2Title' => 'Additional Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1604', 'pel2Number' => '2.04', 'pel2Title' => 'Presentation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1607', 'pel2Number' => 'R3133-PEM-405', 'pel2Title' => 'IMR/OMM Development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1610', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1610', 'pel2Number' => '2.01', 'pel2Title' => 'Marine Growth Cleaner Concept Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1610', 'pel2Number' => '3.01', 'pel2Title' => 'Soft Landing Concept Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1610', 'pel2Number' => '4.01', 'pel2Title' => 'Anode Clamp', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1611', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1611', 'pel2Number' => '2.01', 'pel2Title' => 'Free Span Shape Verification', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1611', 'pel2Number' => '2.02', 'pel2Title' => 'Free Span and Mitigation Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1613', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1613', 'pel2Number' => '1.02', 'pel2Title' => 'Meeting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1613', 'pel2Number' => '2.01', 'pel2Title' => 'Engineering Consultancy', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1613', 'pel2Number' => '2.02', 'pel2Title' => 'Additional Order 1', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1613', 'pel2Number' => '2.03', 'pel2Title' => 'Additional Order 2', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1618', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1618', 'pel2Number' => '2.01', 'pel2Title' => 'FEED Endorsement', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1624', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1624', 'pel2Number' => '2.01', 'pel2Title' => 'Repairs of PRP Riser', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1626', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1626', 'pel2Number' => '2.01', 'pel2Title' => 'Engineering Consultancy', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1629', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1629', 'pel2Number' => '2.01', 'pel2Title' => 'Riser Assessment', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1629', 'pel2Number' => '3.01', 'pel2Title' => 'Structural Assessment', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1629', 'pel2Number' => '4.01', 'pel2Title' => 'Design of Temporary and Permanent Riser Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1629', 'pel2Number' => '5.01', 'pel2Title' => 'In-Service Welding Specification', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1629', 'pel2Number' => '6.01', 'pel2Title' => 'Certification of Professional Eng Lic', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1632', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1632', 'pel2Number' => '2.01', 'pel2Title' => '56 Flare Stack Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1635', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1635', 'pel2Number' => '2.01', 'pel2Title' => 'Hold Down Lug Assessment', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1636', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1636', 'pel2Number' => '2.01', 'pel2Title' => 'Review Geo Survey Information', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1636', 'pel2Number' => '2.02', 'pel2Title' => 'Review and Endorse Design Doc', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1636', 'pel2Number' => '2.03', 'pel2Title' => 'Review and Endorse PSI Report', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1636', 'pel2Number' => '2.04', 'pel2Title' => 'Foundation Design Parameters', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1636', 'pel2Number' => '2.05', 'pel2Title' => 'Foundation Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1646', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1646', 'pel2Number' => '2.01', 'pel2Title' => 'Base Model Development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1646', 'pel2Number' => '2.02', 'pel2Title' => 'Sensitivity and Reliability Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1647', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1647', 'pel2Number' => '2.01', 'pel2Title' => 'Concept Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1647', 'pel2Number' => '2.02', 'pel2Title' => 'Detail Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1647', 'pel2Number' => '2.03', 'pel2Title' => 'FAT', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1647', 'pel2Number' => '3.01', 'pel2Title' => 'Diverless Clamp Study', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1648', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1648', 'pel2Number' => '2.01', 'pel2Title' => 'Engineering Support - ML', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1648', 'pel2Number' => '2.02', 'pel2Title' => 'Engineering Support - TH', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1648', 'pel2Number' => '2.03', 'pel2Title' => 'Fatigue analysis for PL Fault Crossing', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1648', 'pel2Number' => '2.04', 'pel2Title' => 'Fatigue analysis for10 Free Sapn', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1650', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1650', 'pel2Number' => '2.01', 'pel2Title' => 'Benchmark', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1653', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1653', 'pel2Number' => '2.01', 'pel2Title' => 'Engineering Consultancy', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1705', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1705', 'pel2Number' => '2.01', 'pel2Title' => 'Engineering Phase 1', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1705', 'pel2Number' => '2.02', 'pel2Title' => 'Engineering Phase 2', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1705', 'pel2Number' => '2.03', 'pel2Title' => 'Engineering Phase 3', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1706', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1706', 'pel2Number' => '2.01', 'pel2Title' => 'Base Model Development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1706', 'pel2Number' => '2.02', 'pel2Title' => 'Mooring Anlaysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1706', 'pel2Number' => '3.01', 'pel2Title' => 'Software lease', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1706', 'pel2Number' => '4.01', 'pel2Title' => 'Presentation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1711', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1711', 'pel2Number' => '2.01', 'pel2Title' => 'Engineering', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1715', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1715', 'pel2Number' => '2.01', 'pel2Title' => 'Engineering', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1721', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1721', 'pel2Number' => '2.01', 'pel2Title' => 'Design Basis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1721', 'pel2Number' => '2.03', 'pel2Title' => 'Start Up Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1721', 'pel2Number' => '2.04', 'pel2Title' => 'Noraml Lay Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1721', 'pel2Number' => '2.05', 'pel2Title' => 'Shore Pull Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1721', 'pel2Number' => '3.01', 'pel2Title' => 'COR Normal Lay Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1721', 'pel2Number' => '3.02', 'pel2Title' => 'COR Shore Pull Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1723', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1723', 'pel2Number' => '2.01', 'pel2Title' => 'Freespan Training', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1724', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1724', 'pel2Number' => '2.01', 'pel2Title' => 'FEA Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1724', 'pel2Number' => '2.01', 'pel2Title' => 'ECA Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '1.01', 'pel2Title' => 'Project Mangement', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.1.1', 'pel2Title' => 'Review and endorsement', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.1.2', 'pel2Title' => 'Basis of design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.2', 'pel2Title' => 'Field layout and general', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.2a', 'pel2Title' => 'Field layout and general, Route Selection Report', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.3', 'pel2Title' => 'Production flowline', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.6', 'pel2Title' => 'Production FLETs and subsea pig launcher/receiver', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.6a', 'pel2Title' => 'Production FLETs and subsea pig launcher/receiver, FLET and PLR Design Premises', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.6b', 'pel2Title' => 'Production FLETs and subsea pig launcher/receiver, FLET and PLR Structure Design Report', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.6c', 'pel2Title' => 'Production FLETs and subsea pig launcher/receiver, FLET and PLR Drafting', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.7', 'pel2Title' => 'Well Jumper In-place analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.8', 'pel2Title' => 'Close-out support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1727', 'pel2Number' => '9.4.9', 'pel2Title' => 'Rivise bid engineering support (WO5)', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1728', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1728', 'pel2Number' => '2.01', 'pel2Title' => 'Geotechnical Consultancy', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1728', 'pel2Number' => '2.02', 'pel2Title' => 'Cost Estimation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1742', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1742', 'pel2Number' => '2.01', 'pel2Title' => 'Flowline sizing', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1742', 'pel2Number' => '2.02', 'pel2Title' => 'Cost Estimation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1755', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1755', 'pel2Number' => '2.01', 'pel2Title' => 'Procedure development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1733', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1733', 'pel2Number' => '2.01', 'pel2Title' => 'Engineering', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1734', 'pel2Number' => '1.01', 'pel2Title' => 'Project Mangement', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1734', 'pel2Number' => '2.01', 'pel2Title' => 'PSI Development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1734', 'pel2Number' => '2.02', 'pel2Title' => 'Trenchability Assessment', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1734', 'pel2Number' => '3.01', 'pel2Title' => 'PLET and ILT Foundation Evaluation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1734', 'pel2Number' => '4.01', 'pel2Title' => 'Bid Enigineering Support (WO4)', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1743', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1743', 'pel2Number' => '2.01', 'pel2Title' => 'Skin Friction and Bearing Capacity Plots', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1746', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1746', 'pel2Number' => '2.01', 'pel2Title' => 'Soil Settlement', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1746', 'pel2Number' => '2.02', 'pel2Title' => 'Soil Improvement', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1746', 'pel2Number' => '2.03', 'pel2Title' => 'Selection of fill materials and slope stability', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1746', 'pel2Number' => '2.04', 'pel2Title' => 'Additional Work', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1815', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1812', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1812', 'pel2Number' => '2.02', 'pel2Title' => 'Seismic Hazard Analysis and Design for Subsea Pipeline and Riser', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1815', 'pel2Number' => '2.01', 'pel2Title' => 'FEED Endorsement and geotechnical assessment assessment', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1816', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1816', 'pel2Number' => '2.01', 'pel2Title' => 'Geotechnical Design', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1816', 'pel2Number' => '3.01', 'pel2Title' => 'Installation Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1817', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1817', 'pel2Number' => '2.02', 'pel2Title' => 'Fitness for Service', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1817', 'pel2Number' => '3.01', 'pel2Title' => 'Training', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1821', 'pel2Number' => '2.02', 'pel2Title' => 'Engineering Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1823', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1823', 'pel2Number' => '2.01', 'pel2Title' => 'Bid Engineering Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1828', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1828', 'pel2Number' => '2.01', 'pel2Title' => 'Clamping Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1830', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1830', 'pel2Number' => '2.01', 'pel2Title' => 'Design Basis Development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1830', 'pel2Number' => '2.02', 'pel2Title' => 'Cable Spooling Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1830', 'pel2Number' => '2.03', 'pel2Title' => 'Cable Laying Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1830', 'pel2Number' => '2.04', 'pel2Title' => 'Beach Cable Pull-in Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1830', 'pel2Number' => '2.05', 'pel2Title' => 'Change order', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1830', 'pel2Number' => '9.01', 'pel2Title' => 'Software Service: Orcaflex', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1831', 'pel2Number' => '2.01', 'pel2Title' => 'Design Basis Development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1831', 'pel2Number' => '2.02', 'pel2Title' => 'Cable Lay Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1831', 'pel2Number' => '2.03', 'pel2Title' => 'Beach Cable Pull-in Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1833', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1833', 'pel2Number' => '2.02', 'pel2Title' => 'Engineering Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1834', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1834', 'pel2Number' => '2.01', 'pel2Title' => 'Bid Engineering Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1834', 'pel2Number' => '2.02', 'pel2Title' => 'Bid Engineering Support (Structural Aspect)', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1835', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1835', 'pel2Number' => '2.01', 'pel2Title' => 'Bid Engineering Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1836', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1836', 'pel2Number' => '2.02', 'pel2Title' => 'Penetration analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1837', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1837', 'pel2Number' => '2.02', 'pel2Title' => 'Retreival Analysis', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1845', 'pel2Number' => '2.01', 'pel2Title' => 'Design Basis Development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1845', 'pel2Number' => '2.02', 'pel2Title' => 'Riser Integrity Assessment', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1851', 'pel2Number' => '1.01', 'pel2Title' => 'Project Management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1851', 'pel2Number' => '1.02', 'pel2Title' => 'Project Engineering Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1851', 'pel2Number' => '2.02', 'pel2Title' => 'Engineering Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => '1851', 'pel2Number' => '2.03', 'pel2Title' => 'Drafting Support', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A161', 'pel2Number' => '1.01', 'pel2Title' => 'ISO training course', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A161', 'pel2Number' => '2.01', 'pel2Title' => 'Contact and appoint ISO consultant', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A161', 'pel2Number' => '3.01', 'pel2Title' => 'ISO implementation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A161', 'pel2Number' => '4.01', 'pel2Title' => 'ISO Accreditation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A162', 'pel2Number' => '1.01', 'pel2Title' => 'Status Review', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A162', 'pel2Number' => '2.01', 'pel2Title' => 'Prospect search', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A162', 'pel2Number' => '3.01', 'pel2Title' => 'Prospect selection', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A162', 'pel2Number' => '4.01', 'pel2Title' => 'Qualification', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A163', 'pel2Number' => '1.01', 'pel2Title' => 'Timesheet specification', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A163', 'pel2Number' => '1.02', 'pel2Title' => 'Timesheet development', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A164', 'pel2Number' => '1.01', 'pel2Title' => 'Employee benefit set up', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A171', 'pel2Number' => '1.01', 'pel2Title' => 'Scope search', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A171', 'pel2Number' => '2.01', 'pel2Title' => 'Approch Strategh', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A171', 'pel2Number' => '3.01', 'pel2Title' => 'Partnership engagement', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A172', 'pel2Number' => '1.01', 'pel2Title' => 'Insurance Agency', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A173', 'pel2Number' => '1.01', 'pel2Title' => 'Office Relocation', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A173', 'pel2Number' => '2.01', 'pel2Title' => 'Office Layout', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A181', 'pel2Number' => '1.01', 'pel2Title' => 'Project management', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A181', 'pel2Number' => '2.01', 'pel2Title' => 'PVF Survey', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A181', 'pel2Number' => '2.02', 'pel2Title' => 'PVF Service provide contact', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A181', 'pel2Number' => '2.03', 'pel2Title' => 'PVF Selection', 'create_by' => 'SYSTEM'],
       ['tel1Number' => 'A181', 'pel2Number' => '2.04', 'pel2Title' => 'PVF Application and completion', 'create_by' => 'SYSTEM'],
     ];

     // Insert data
     foreach($records as $record)
     {
       // $department['active'] = 1;
       App\pel2::create($record);
     }
   }
 }
